SIMULAT_DIR := $(CURDIR)

include $(SIMULAT_DIR)/Files.mk

SIMULAT_EXEC := $(EXEC)
SIMULAT_SRC := $(SRC)
SIMULAT_OBJ := $(OBJ)
SIMULAT_DEP := $(DEPENDS)
SIMULAT_DESTDIR := $(DST)
SIMULAT_ABSDESTDIR := $(abspath $(SIMULAT_DESTDIR))

build-$(TARGET): destdir-$(SIMULAT_EXEC)		\
			$(SIMULAT_DESTDIR)/$(SIMULAT_EXEC) $(BUILD_DEP)

$(SIMULAT_DESTDIR)/$(SIMULAT_EXEC): $(SIMULAT_OBJ)
	$(CC) -o $@ $< $(LDFLAGS)

$(SIMULAT_DESTDIR)/%.o: $(SIMULAT_DIR)/%.c
	$(CC) -o $@ -c $< $(CFLAGS) -MMD

$(SIMULAT_ABSDESTDIR):
	mkdir -p $(SIMULAT_ABSDESTDIR)

destdir-$(EXEC): $(SIMULAT_ABSDESTDIR)

.PHONY: clean-$(SIMULAT_EXEC) mrproper-$(SIMULAT_EXEC)

clean-$(SIMULAT_EXEC):
	rm -f $(SIMULAT_ABSDESTDIR)/*.o
	rm -f $(SIMULAT_ABSDESTDIR)/*.d

mrproper-$(SIMULAT_EXEC): clean
ifneq ($(SIMULAT_ABSDESTDIR),$(realpath $(SIMULAT_DIR)))
	rm -rf $(SIMULAT_ABSDESTDIR)
else
	rm -f $(SIMULAT_ABSDESTDIR)/$(SIMULAT_EXEC)
endif

-include $(RULESMK_DEP)
-include $(SIMULAT_DEP)
